version: '3.2'

services:

  frontend:
    build: frontend
    ports:
      - 20080:80
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app
    environment:
      - YII_ENV=dev
      - YII_DEBUG=1

  backend:
    build: backend
    ports:
      - 21080:80
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app
    environment:
      - YII_ENV=dev
      - YII_DEBUG=1

  # Uncomment if using PostgreSQL instead
  # pgsql:
  #   image: postgres:9.5
  #   environment:
  #     - POSTGRES_DB=yii2advanced
  #     - POSTGRES_USER=yii2advanced
  #     - POSTGRES_PASSWORD=secret
